replace minDistToCells by distToCells
BodenmillerGroup/imcRtools pull request #125
Opened 2024-06-21 12:31 UTC by brunopalau

Replaced minDistToCells function by superior distToCells function, which contains minDistToCells but also allows the user to specify the "metric" parameter and therefore compute min, max, mean and median distances to cells of interest, while exactly mimicking the minDistToCells output when using metric="min"

2024-06-21 12:53 UTC, nilseling commented
Awesome, would also be good to add this to NEWS and issue a version bump.

2024-06-21 15:01 UTC, lassedochreden commented
@nilseling thats my job now ;)

2024-06-25 07:42 UTC, lassedochreden requested changes
Hi @brunopalau, great job! See my comments - Also as @nilseling suggested above, please update the `NEWS` and perform a version bump (to 1.11.1 I think - will double-check)

2024-06-25 07:42 UTC, lassedochreden commented on R/distToCells.R
> +#' @param metric one of "min", "max", "mean" or "meadian" specifying the distance metric to use when computing
please correct to "median"

2024-06-25 07:42 UTC, lassedochreden commented on R/distToCells.R
> +#' @author Daniel Schulz & Bruno Palau (\email{daniel.schulz@@uzh.ch})
(optional) add your mail

2024-06-25 07:42 UTC, lassedochreden commented on R/distToCells.R
> +        dist_mat <- distances::distances(as.matrix(colData(cur_obj)[,
I think you do not need to specify the package here, since you import it above > distances(as.matrix(colData(cur_obj)[,coords])) should be enough

2024-06-25 07:42 UTC, lassedochreden commented on R/distToCells.R
>        cur_obj[[name]] <- dist_to_patch
as we discussed, potentially worthwhile to alter the new colData `name` entry depending on the metric chosen, so the user does not overwrite distToCells straight away with a new metric (e.g. if user chooses `max`, the entry could be called `maxDistToCells`)

2024-06-25 07:42 UTC, lassedochreden commented on tests/testthat/test_distToCells.R
> +test_that("distToCells works",{
I think here you just copied the tests four times depending on the metric, which is okay but not totally necessary. Would be good to have some tests that numerically test the differences between all the metrics for a given image.

2024-06-25 07:42 UTC, lassedochreden commented on tests/testthat/test_distToCells.R
> +  # TODO: for all cases, enforces that a cells not of interest and a cell of interect do not have the same exact coordinates
is this a new TODO?

2025-06-26 12:01 UTC, lassedochreden reviewed
looks good to me :) @SchulzDan check it out and merge, if you agree - We should merge this first and then the "plotInteractions" PR.

2025-06-26 12:01 UTC, lassedochreden commented on vignettes/imcRtools.Rmd
> +Calculate the min, max, mean or median distance for each cell to a given cell type or class of
"To calculate..."

2025-06-26 13:22 UTC, SchulzDan commented
Should we maybe replace the "metric" argument in the function with something more aligned with other packages? E.g. "summary_fun", "fun" or "statistics"?

2025-07-04 06:37 UTC, SchulzDan approved these changes
Looks good, let's merge

2025-07-04 07:57 UTC, lassedochreden approved these changes

2025-07-04 07:57 UTC, lassedochreden commented on R/distToCells.R
> +        dist_mat <- distances::distances(as.matrix(colData(cur_obj)[,
do you need to use the distances:: namespace call here? I do not think so. Maybe remove.

2025-07-04 10:08 UTC, merged