Community detection function
BodenmillerGroup/imcRtools pull request #87
Opened 2022-09-20 10:34 UTC by lassedochreden

Hi @nilseling, 

here is the first version of the `detectCommunity` function. 

Happy to discuss!

2022-10-13 19:05 UTC, nilseling requested changes
Let's discuss these two points again. But well done! Love the docs!

2022-10-13 19:05 UTC, nilseling commented on R/detectCommunity.R
> +                            size_threshold = 10,
Should we enforce a threshold as default? Why mot keep it `0`?

2022-10-13 19:05 UTC, nilseling commented
Great work! Nearly ready to merge. Do you mind bumping the version, adjusting NEWS and adding the function to the vignette?

2022-10-14 08:52 UTC, lassedochreden commented on R/detectCommunity.R
> +      names(comm) <- colnames(cur_object)
Good point! For now, I added a **validity check**.

2022-10-14 20:28 UTC, nilseling approved these changes
Looks nice!

2022-10-14 20:28 UTC, merged